######################################################################################
##     ___                                  _         _____
##    /   \ _   _  _ __    __ _  _ __ ___  (_)  ___  /__   \ _ __   ___   ___  ___
##   / /\ /| | | || '_ \  / _` || '_ ` _ \ | | / __|   / /\/| '__| / _ \ / _ \/ __|
##  / /_// | |_| || | | || (_| || | | | | || || (__   / /   | |   |  __/|  __/\__ \
## /___,'   \__, ||_| |_| \__,_||_| |_| |_||_| \___|  \/    |_|    \___| \___||___/
##          |___/
##
## Configuration file, for details see https://github.com/Kiro47/DynamicTrees
## Author: Kiro47
######################################################################################
version: 0.1