######################################################################################
##     ___                                  _         _____
##    /   \ _   _  _ __    __ _  _ __ ___  (_)  ___  /__   \ _ __   ___   ___  ___
##   / /\ /| | | || '_ \  / _` || '_ ` _ \ | | / __|   / /\/| '__| / _ \ / _ \/ __|
##  / /_// | |_| || | | || (_| || | | | | || || (__   / /   | |   |  __/|  __/\__ \
## /___,'   \__, ||_| |_| \__,_||_| |_| |_||_| \___|  \/    |_|    \___| \___||___/
##          |___/
##
## Configuration file, for details see https://github.com/Kiro47/DynamicTrees
## Author: Kiro47
######################################################################################
version: 0.1
AutoReplant:
  Enabled: true
  # If there is a "tree" (Log or Sapling) within X of the floating sapling do
  # not auto plant it. If at 0, always attempt to plant the sapling.
#  NearestTree: 0 ## Currently not implemented
  # Maximum radial range for replanting
  # 0 Allows for infinite range
  # High ranges can result in possibly heavy lag spikes.
#  ReplantRange: 20 ## Currently not implemented.
  # Amount of seconds before the sapling will replant itself
  # 0 Will cause it to attempt to replant immediately, however is not advised
  # as it will become near impossible for players to pick them up.
  ReplantTime: 5
